DOMAIN = "frakon_dashboard"
STORAGE_KEY = "frakon_dashboard.dashboards"
STORAGE_VERSION = 1
DATA_BACKEND = "backend"
DATA_WEBSOCKET_REGISTERED = "websocket_registered"

READABLE_DOCUMENT_VERSIONS = frozenset({1, 2})
WRITABLE_DOCUMENT_VERSIONS = frozenset({1})

RESPONSIVE_CANVAS_V2_KIND = "responsive-canvas-v2"
READABLE_RESPONSIVE_BUNDLE_KINDS = frozenset({RESPONSIVE_CANVAS_V2_KIND})
WRITABLE_RESPONSIVE_BUNDLE_KINDS = frozenset()
