import type{DashboardEmergencyExecutionPlan}from'./dashboard-emergency-action-execution';import type{DashboardEmergencyExecutionSnapshot}from'./dashboard-emergency-action-executor';import type{DashboardEmergencyExecutionJournalStore}from'./dashboard-emergency-execution-journal';
export interface DashboardEmergencyIdempotencyRecord{key:string;createdAt:number;completedAt?:number;status:'started'|'completed'|'failed'}
export interface DashboardEmergencyIdempotencyStore{get(key:string):DashboardEmergencyIdempotencyRecord|undefined;set(record:DashboardEmergencyIdempotencyRecord):boolean|void;journal?:DashboardEmergencyExecutionJournalStore}
export type DashboardEmergencyIdempotencyBeginResult='started'|'duplicate'|'storage-failed';
export function dashboardEmergencyIdempotencyKey(plan:DashboardEmergencyExecutionPlan,snapshot:DashboardEmergencyExecutionSnapshot):string{return [snapshot.incidentOccurrenceId??snapshot.incidentSignature,plan.action.kind,plan.action.entityId??'',plan.action.domain??'',plan.action.service??''].join('|')}
export function claimDashboardEmergencyIdempotentExecution(store:DashboardEmergencyIdempotencyStore,key:string,now=Date.now()):DashboardEmergencyIdempotencyBeginResult{const existing=store.get(key);if(existing&&(existing.status==='started'||existing.status==='completed'))return'duplicate';const persisted=store.set({key,createdAt:now,status:'started'});return persisted===false?'storage-failed':'started'}
export function beginDashboardEmergencyIdempotentExecution(store:DashboardEmergencyIdempotencyStore,key:string,now=Date.now()):boolean{return claimDashboardEmergencyIdempotentExecution(store,key,now)==='started'}
export function finishDashboardEmergencyIdempotentExecution(store:DashboardEmergencyIdempotencyStore,key:string,status:'completed'|'failed',now=Date.now()):boolean{const existing=store.get(key);return store.set({key,createdAt:existing?.createdAt??now,completedAt:now,status})!==false}
export class MemoryDashboardEmergencyIdempotencyStore implements DashboardEmergencyIdempotencyStore{private readonly records=new Map<string,DashboardEmergencyIdempotencyRecord>();get(key:string){return this.records.get(key)}set(record:DashboardEmergencyIdempotencyRecord){this.records.set(record.key,record);return true}}
