export const DASHBOARD_EMERGENCY_RECOVERY_RESOLUTION_STORAGE_KEY='frakon.dashboard.emergency-recovery-resolution.v2';
export const DASHBOARD_EMERGENCY_RECOVERY_RESOLUTION_MAX_AGE_MS=365*24*60*60*1000;
export const DASHBOARD_EMERGENCY_RECOVERY_RESOLUTION_MAX_RECORDS=500;
export interface DashboardEmergencyResolvedRecovery{occurrenceId:string;incidentSignature:string;resolvedAt:number}
export function loadDashboardEmergencyResolvedRecoveries(storage:Pick<Storage,'getItem'>|undefined,key=DASHBOARD_EMERGENCY_RECOVERY_RESOLUTION_STORAGE_KEY):DashboardEmergencyResolvedRecovery[]{if(!storage)return[];try{const raw=storage.getItem(key);if(!raw)return[];const parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed.map(parseRecord).filter((record):record is DashboardEmergencyResolvedRecovery=>record!==undefined):[]}catch{return[]}}
export function saveDashboardEmergencyResolvedRecovery(storage:Pick<Storage,'getItem'|'setItem'>|undefined,occurrenceId:string,incidentSignature:string,resolvedAt=Date.now(),key=DASHBOARD_EMERGENCY_RECOVERY_RESOLUTION_STORAGE_KEY):DashboardEmergencyResolvedRecovery[]{const records=loadDashboardEmergencyResolvedRecoveries(storage,key).filter(record=>record.occurrenceId!==occurrenceId);records.push({occurrenceId,incidentSignature,resolvedAt});return persist(storage,records,key)}
export function pruneDashboardEmergencyResolvedRecoveries(storage:Pick<Storage,'getItem'|'setItem'>|undefined,protectedOccurrenceIds:string[]=[],now=Date.now(),maxAgeMs=DASHBOARD_EMERGENCY_RECOVERY_RESOLUTION_MAX_AGE_MS,maxRecords=DASHBOARD_EMERGENCY_RECOVERY_RESOLUTION_MAX_RECORDS,key=DASHBOARD_EMERGENCY_RECOVERY_RESOLUTION_STORAGE_KEY):DashboardEmergencyResolvedRecovery[]{const protectedIds=new Set(protectedOccurrenceIds),records=loadDashboardEmergencyResolvedRecoveries(storage,key),fresh=records.filter(record=>protectedIds.has(record.occurrenceId)||now-record.resolvedAt<=maxAgeMs),protectedRecords=fresh.filter(record=>protectedIds.has(record.occurrenceId)),unprotected=fresh.filter(record=>!protectedIds.has(record.occurrenceId)).sort((a,b)=>b.resolvedAt-a.resolvedAt).slice(0,Math.max(0,maxRecords-protectedRecords.length));return persist(storage,[...protectedRecords,...unprotected].sort((a,b)=>b.resolvedAt-a.resolvedAt),key)}
export function isDashboardEmergencyRecoveryResolved(records:DashboardEmergencyResolvedRecovery[],occurrenceId:string):boolean{return records.some(record=>record.occurrenceId===occurrenceId)}
function persist(storage:Pick<Storage,'setItem'>|undefined,records:DashboardEmergencyResolvedRecovery[],key:string):DashboardEmergencyResolvedRecovery[]{if(storage)try{storage.setItem(key,JSON.stringify(records))}catch{return records}return records}
function parseRecord(value:unknown):DashboardEmergencyResolvedRecovery|undefined{if(!value||typeof value!=='object')return undefined;const record=value as Record<string,unknown>;if(typeof record.occurrenceId==='string'&&typeof record.incidentSignature==='string'&&typeof record.resolvedAt==='number')return{occurrenceId:record.occurrenceId,incidentSignature:record.incidentSignature,resolvedAt:record.resolvedAt};return undefined}
