import {describe,expect,it,vi} from 'vitest';import {createDashboardEmergencyExecutionPlan} from './dashboard-emergency-action-execution';import {executeDashboardEmergencyPlan} from './dashboard-emergency-action-executor';
const plan=()=>createDashboardEmergencyExecutionPlan({kind:'close-water',domain:'valve',service:'close_valve',entityId:'valve.main_water'},{active:true,acknowledged:false,emergencyKind:'water'});
const snap=(state='open')=>({incidentSignature:'water:1',incidentActive:true,entityState:state,capturedAt:1});
describe('Emergency guarded executor',()=>{
 it('executes an unchanged confirmed plan exactly once',async()=>{const callService=vi.fn().mockResolvedValue(undefined);expect(await executeDashboardEmergencyPlan(plan(),{callService},snap(),snap(),true)).toEqual({status:'executed'});expect(callService).toHaveBeenCalledWith('valve','close_valve',{entity_id:'valve.main_water'});});
 it('blocks unconfirmed physical actions',async()=>{const callService=vi.fn();expect((await executeDashboardEmergencyPlan(plan(),{callService},snap(),snap(),false)).status).toBe('blocked');expect(callService).not.toHaveBeenCalled();});
 it('rejects stale incident and changed entity state',async()=>{const callService=vi.fn();expect((await executeDashboardEmergencyPlan(plan(),{callService},snap(),{...snap(),incidentActive:false},true)).status).toBe('stale');expect((await executeDashboardEmergencyPlan(plan(),{callService},snap(),snap('closed'),true)).status).toBe('stale');expect(callService).not.toHaveBeenCalled();});
 it('rejects a new occurrence of the same base incident',async()=>{const callService=vi.fn(),planned={...snap(),incidentOccurrenceId:'water:1@@100'},current={...snap(),incidentOccurrenceId:'water:1@@200'};expect((await executeDashboardEmergencyPlan(plan(),{callService},planned,current,true)).status).toBe('stale');expect(callService).not.toHaveBeenCalled();});
 it('suppresses double execution while the first call is in flight',async()=>{let release!:()=>void;const callService=vi.fn(()=>new Promise<void>(resolve=>{release=resolve}));const p=createDashboardEmergencyExecutionPlan({kind:'close-water',domain:'valve',service:'close_valve',entityId:'valve.main_water'},{active:true,acknowledged:false,emergencyKind:'water'});const first=executeDashboardEmergencyPlan(p,{callService},snap(),snap(),true);await Promise.resolve();expect((await executeDashboardEmergencyPlan(p,{callService},snap(),snap(),true)).status).toBe('duplicate');release();expect((await first).status).toBe('executed');expect(callService).toHaveBeenCalledTimes(1);});
 it('allows a new occurrence while the previous occurrence is still in flight',async()=>{const releases:Array<()=>void>=[];const callService=vi.fn(()=>new Promise<void>(resolve=>{releases.push(resolve)}));const firstSnapshot={...snap(),incidentOccurrenceId:'water:1@@100'},secondSnapshot={...snap(),incidentOccurrenceId:'water:1@@200'};const first=executeDashboardEmergencyPlan(plan(),{callService},firstSnapshot,firstSnapshot,true);await Promise.resolve();const second=executeDashboardEmergencyPlan(plan(),{callService},secondSnapshot,secondSnapshot,true);await Promise.resolve();expect(callService).toHaveBeenCalledTimes(2);releases.forEach(release=>release());expect((await first).status).toBe('executed');expect((await second).status).toBe('executed');});
});
