import type{DashboardEmergencyExecutionPlan}from'./dashboard-emergency-action-execution';import type{DashboardEmergencyExecutionResult}from'./dashboard-emergency-action-executor';import type{DashboardEmergencyVerificationResult}from'./dashboard-emergency-action-verification';
export interface DashboardEmergencyActionAuditEntry{id:string;incidentSignature:string;incidentOccurrenceId?:string;createdAt:number;planId:string;kind:string;entityId?:string;domain?:string;service?:string;policyLevel:string;confirmed?:boolean;executedAt?:number;executionStatus?:DashboardEmergencyExecutionResult['status'];executionReason?:string;verificationStatus?:DashboardEmergencyVerificationResult['status'];verifiedState?:string;verificationReason?:string}
export function createDashboardEmergencyActionAuditEntry(plan:DashboardEmergencyExecutionPlan,incidentSignature:string,now=Date.now(),incidentOccurrenceId?:string):DashboardEmergencyActionAuditEntry{return{id:`${now}:${plan.id}`,incidentSignature,incidentOccurrenceId,createdAt:now,planId:plan.id,kind:plan.action.kind,entityId:plan.action.entityId,domain:plan.call?.domain,service:plan.call?.service,policyLevel:plan.policy.level}}
export function recordDashboardEmergencyConfirmation(entry:DashboardEmergencyActionAuditEntry,confirmed:boolean):DashboardEmergencyActionAuditEntry{return{...entry,confirmed}}
export function recordDashboardEmergencyExecution(entry:DashboardEmergencyActionAuditEntry,result:DashboardEmergencyExecutionResult,now=Date.now()):DashboardEmergencyActionAuditEntry{return{...entry,executedAt:now,executionStatus:result.status,executionReason:result.reason}}
export function recordDashboardEmergencyVerification(entry:DashboardEmergencyActionAuditEntry,result:DashboardEmergencyVerificationResult):DashboardEmergencyActionAuditEntry{return{...entry,verificationStatus:result.status,verifiedState:result.actualState,verificationReason:result.reason}}
export function dashboardEmergencyActionAuditMatches(entry:DashboardEmergencyActionAuditEntry,incidentSignature:string,incidentOccurrenceId?:string):boolean{return incidentOccurrenceId!==undefined?entry.incidentOccurrenceId===incidentOccurrenceId:entry.incidentSignature===incidentSignature}
export function dashboardEmergencyActionAuditOccurrenceKey(entry:DashboardEmergencyActionAuditEntry):string{return entry.incidentOccurrenceId??entry.incidentSignature}
export function appendDashboardEmergencyActionAudit(entries:DashboardEmergencyActionAuditEntry[],entry:DashboardEmergencyActionAuditEntry,limit=200):DashboardEmergencyActionAuditEntry[]{return[entry,...entries.filter(item=>item.id!==entry.id)].slice(0,Math.max(1,limit))}
