import { describe, expect, it } from 'vitest';
import { emergencyKind, emergencyTitle, humanizeEntityId, presentDashboardEmergency, presentDashboardEmergencyDiagnostic } from './dashboard-emergency-presentation';
import type { DashboardEmergencyFocusTarget } from './dashboard-emergency-focus';

const target:DashboardEmergencyFocusTarget={itemId:'smoke',item:{id:'smoke',x:0,y:0,w:3,h:2,card:{type:'sensor'}},severity:'critical',reasons:['binary_sensor.kitchen_smoke reports an active smoke condition'],sourceEntityIds:['binary_sensor.kitchen_smoke'],sourceEntityLabels:{'binary_sensor.kitchen_smoke':'Kouřové čidlo kuchyň'}};

describe('Emergency Focus presentation',()=>{
 it('turns smoke metadata into a concise user-facing alert using friendly_name',()=>{ expect(presentDashboardEmergency(target)).toMatchObject({title:'Smoke detected',kind:'smoke',icon:'◉',sourceLabel:'Kouřové čidlo kuchyň',technicalReason:'binary_sensor.kitchen_smoke reports an active smoke condition',sourceEntityId:'binary_sensor.kitchen_smoke'}); });
 it('localizes known safety conditions and guidance',()=>{ const czech=presentDashboardEmergency(target,'cs-CZ'); expect(czech.title).toBe('Detekován kouř'); expect(czech.guidance).toContain('Zkontrolujte'); expect(emergencyTitle('binary_sensor.gas reports an active gas condition','de')).toBe('Gas erkannt'); expect(emergencyTitle('binary_sensor.leak reports an active moisture condition','sk')).toBe('Detegovaný únik vody'); expect(emergencyTitle('alarm_control_panel.home is in alarm state triggered','pl')).toBe('Aktywny alarm bezpieczeństwa'); });
 it('classifies visual event types independently of locale',()=>{ expect(emergencyKind('binary_sensor.smoke reports an active smoke condition')).toBe('smoke'); expect(emergencyKind('binary_sensor.gas reports an active gas condition')).toBe('gas'); expect(emergencyKind('binary_sensor.leak reports an active moisture condition')).toBe('water'); expect(emergencyKind('alarm_control_panel.home is in alarm state triggered')).toBe('alarm'); expect(emergencyKind('sensor.ups_battery has a low battery')).toBe('battery'); expect(emergencyKind('climate.home reports a climate problem')).toBe('climate'); expect(emergencyKind('camera.gate is unavailable')).toBe('unavailable'); });
 it('humanizes Home Assistant entity ids when friendly_name is unavailable',()=>{ expect(humanizeEntityId('binary_sensor.kitchen_smoke')).toBe('Kitchen Smoke'); });
 it('builds a localized diagnostic summary with area, source and live duration',()=>{ const diagnostic=presentDashboardEmergencyDiagnostic({signature:'water',itemId:'water',sourceEntityIds:['binary_sensor.water'],sourceEntityLabels:{'binary_sensor.water':'Čidlo vody'},sourceEntityMetadata:{'binary_sensor.water':{areaName:'Technická místnost',deviceName:'Aqara Water Leak Sensor'}},reasons:['binary_sensor.water reports an active moisture condition'],startedAt:1_000},'cs-CZ',121_000); expect(diagnostic).toMatchObject({title:'Detekován únik vody',sourceLabel:'Čidlo vody',areaName:'Technická místnost',deviceName:'Aqara Water Leak Sensor',durationLabel:'2 min',summary:'Detekován únik vody · Technická místnost · Čidlo vody — stav trvá 2 min'}); });
 it('describes ended events in the past tense',()=>{ const diagnostic=presentDashboardEmergencyDiagnostic({signature:'gas',itemId:'gas',sourceEntityIds:['binary_sensor.gas'],reasons:['binary_sensor.gas reports an active gas condition'],startedAt:1_000,endedAt:61_000},'en',999_000); expect(diagnostic.summary).toContain('condition lasted 1 min'); });
});
