import type { SupportedLanguage } from '../i18n';

export type ResponsiveV2HealthTranslationKey =
  | 'title' | 'status' | 'healthy' | 'blocked' | 'conflict' | 'error' | 'unloaded'
  | 'contract' | 'compatible' | 'read' | 'write' | 'atomicRevision' | 'revisionSync'
  | 'baseRevision' | 'dirtyBreakpoints' | 'conflictBreakpoints' | 'loadEndpoint' | 'dryRunEndpoint' | 'saveEndpoint' | 'removeEndpoint'
  | 'storageNamespace' | 'maxItems' | 'maxConstraints' | 'maxSerializedBytes'
  | 'alphaReadiness' | 'alphaUnavailable' | 'alphaContractMismatch' | 'alphaInstallMismatch' | 'alphaReadReady' | 'alphaDryRunReady' | 'alphaWriteEnabled'
  | 'yes' | 'no' | 'none';

type Messages = Record<ResponsiveV2HealthTranslationKey, string>;

const messages: Record<SupportedLanguage, Messages> = {
  en: { title:'Responsive persistence diagnostics',status:'Status',healthy:'Healthy',blocked:'Blocked',conflict:'Conflict',error:'Error',unloaded:'Not loaded',contract:'Contract',compatible:'Compatible',read:'Read',write:'Write',atomicRevision:'Atomic revision',revisionSync:'Revision sync',baseRevision:'Base revision',dirtyBreakpoints:'Dirty breakpoints',conflictBreakpoints:'Conflict breakpoints',loadEndpoint:'Load endpoint',dryRunEndpoint:'Dry-run endpoint',saveEndpoint:'Save endpoint',removeEndpoint:'Remove endpoint',storageNamespace:'Storage namespace',maxItems:'Max items',maxConstraints:'Max constraints',maxSerializedBytes:'Max bundle bytes',alphaReadiness:'Alpha readiness',alphaUnavailable:'Unavailable',alphaContractMismatch:'Contract mismatch',alphaInstallMismatch:'Install mismatch',alphaReadReady:'Read ready · write locked',alphaDryRunReady:'Dry-run ready · write locked',alphaWriteEnabled:'Write enabled',yes:'yes',no:'no',none:'none' },
  cs: { title:'Diagnostika responsive persistence',status:'Stav',healthy:'V pořádku',blocked:'Zablokováno',conflict:'Konflikt',error:'Chyba',unloaded:'Nenačteno',contract:'Kontrakt',compatible:'Kompatibilní',read:'Čtení',write:'Zápis',atomicRevision:'Atomická revize',revisionSync:'Synchronizace revizí',baseRevision:'Výchozí revize',dirtyBreakpoints:'Změněné breakpointy',conflictBreakpoints:'Konfliktní breakpointy',loadEndpoint:'Endpoint čtení',dryRunEndpoint:'Endpoint ověření bez zápisu',saveEndpoint:'Endpoint zápisu',removeEndpoint:'Endpoint mazání',storageNamespace:'Namespace úložiště',maxItems:'Maximum položek',maxConstraints:'Maximum vazeb',maxSerializedBytes:'Maximum bajtů bundle',alphaReadiness:'Připravenost alpha',alphaUnavailable:'Nedostupné',alphaContractMismatch:'Neshoda kontraktu',alphaInstallMismatch:'Neshoda instalace',alphaReadReady:'Čtení připraveno · zápis zamčen',alphaDryRunReady:'Dry-run připraven · zápis zamčen',alphaWriteEnabled:'Zápis povolen',yes:'ano',no:'ne',none:'žádné' },
  de: { title:'Responsive-Persistenzdiagnose',status:'Status',healthy:'In Ordnung',blocked:'Blockiert',conflict:'Konflikt',error:'Fehler',unloaded:'Nicht geladen',contract:'Vertrag',compatible:'Kompatibel',read:'Lesen',write:'Schreiben',atomicRevision:'Atomare Revision',revisionSync:'Revisionsabgleich',baseRevision:'Basisrevision',dirtyBreakpoints:'Geänderte Breakpoints',conflictBreakpoints:'Konflikt-Breakpoints',loadEndpoint:'Lese-Endpunkt',dryRunEndpoint:'Dry-Run-Endpunkt',saveEndpoint:'Schreib-Endpunkt',removeEndpoint:'Lösch-Endpunkt',storageNamespace:'Speicher-Namespace',maxItems:'Max. Elemente',maxConstraints:'Max. Constraints',maxSerializedBytes:'Max. Bundle-Bytes',alphaReadiness:'Alpha-Bereitschaft',alphaUnavailable:'Nicht verfügbar',alphaContractMismatch:'Vertragsabweichung',alphaInstallMismatch:'Installationsabweichung',alphaReadReady:'Lesen bereit · Schreiben gesperrt',alphaDryRunReady:'Dry-Run bereit · Schreiben gesperrt',alphaWriteEnabled:'Schreiben aktiviert',yes:'ja',no:'nein',none:'keine' },
  sk: { title:'Diagnostika responsive persistence',status:'Stav',healthy:'V poriadku',blocked:'Zablokované',conflict:'Konflikt',error:'Chyba',unloaded:'Nenačítané',contract:'Kontrakt',compatible:'Kompatibilný',read:'Čítanie',write:'Zápis',atomicRevision:'Atomická revízia',revisionSync:'Synchronizácia revízií',baseRevision:'Východisková revízia',dirtyBreakpoints:'Zmenené breakpointy',conflictBreakpoints:'Konfliktné breakpointy',loadEndpoint:'Endpoint čítania',dryRunEndpoint:'Endpoint overenia bez zápisu',saveEndpoint:'Endpoint zápisu',removeEndpoint:'Endpoint mazania',storageNamespace:'Namespace úložiska',maxItems:'Maximum položiek',maxConstraints:'Maximum väzieb',maxSerializedBytes:'Maximum bajtov bundle',alphaReadiness:'Pripravenosť alpha',alphaUnavailable:'Nedostupné',alphaContractMismatch:'Nezhoda kontraktu',alphaInstallMismatch:'Nezhoda inštalácie',alphaReadReady:'Čítanie pripravené · zápis zamknutý',alphaDryRunReady:'Dry-run pripravený · zápis zamknutý',alphaWriteEnabled:'Zápis povolený',yes:'áno',no:'nie',none:'žiadne' },
  pl: { title:'Diagnostyka responsywnej trwałości',status:'Stan',healthy:'W porządku',blocked:'Zablokowane',conflict:'Konflikt',error:'Błąd',unloaded:'Niezaładowane',contract:'Kontrakt',compatible:'Zgodny',read:'Odczyt',write:'Zapis',atomicRevision:'Rewizja atomowa',revisionSync:'Synchronizacja rewizji',baseRevision:'Rewizja bazowa',dirtyBreakpoints:'Zmienione breakpointy',conflictBreakpoints:'Konfliktowe breakpointy',loadEndpoint:'Endpoint odczytu',dryRunEndpoint:'Endpoint walidacji bez zapisu',saveEndpoint:'Endpoint zapisu',removeEndpoint:'Endpoint usuwania',storageNamespace:'Namespace pamięci',maxItems:'Maks. elementów',maxConstraints:'Maks. powiązań',maxSerializedBytes:'Maks. bajtów bundle',alphaReadiness:'Gotowość alpha',alphaUnavailable:'Niedostępne',alphaContractMismatch:'Niezgodność kontraktu',alphaInstallMismatch:'Niezgodność instalacji',alphaReadReady:'Odczyt gotowy · zapis zablokowany',alphaDryRunReady:'Dry-run gotowy · zapis zablokowany',alphaWriteEnabled:'Zapis włączony',yes:'tak',no:'nie',none:'brak' },
};

export function responsiveV2HealthTranslate(language: SupportedLanguage, key: ResponsiveV2HealthTranslationKey): string {
  return messages[language]?.[key] ?? messages.en[key] ?? key;
}
