import {
  buildAutomaticDashboardIntelligenceContext,
  type HomeAssistantStateLike as IntelligenceHomeAssistantState,
} from '../dashboard/dashboard-intelligence-signals';
import type { DashboardDeviceContext, DashboardEntityMetadata, DashboardIntelligenceContext } from '../dashboard/dashboard-intelligence';
import type { DashboardInteractionTracker } from '../dashboard/dashboard-interaction-tracker';
import type { FrakonDashboardDocument, FrakonGridItem } from '../dashboard/layout-model';

export interface HomeAssistantStateLike { entity_id:string; state:string; attributes?:Record<string,unknown>; last_changed?:string; }
export interface HomeAssistantLike { states:Record<string,HomeAssistantStateLike>; language?:string; locale?:{language?:string}; callWS?<T>(message:Record<string,unknown>):Promise<T>; callService?(domain:string,service:string,data?:Record<string,unknown>):Promise<unknown>|unknown; }
export interface HomeAssistantEntityRegistryEntry { entity_id:string; device_id?:string|null; area_id?:string|null; }
export interface HomeAssistantDeviceRegistryEntry { id:string; area_id?:string|null; name?:string|null; name_by_user?:string|null; }
export interface HomeAssistantAreaRegistryEntry { area_id:string; name:string; }
export interface DashboardIntelligenceSignalBridgeOptions { device:DashboardDeviceContext; tracker?:Pick<DashboardInteractionTracker,'snapshot'>; now?:number; entityMetadata?:Record<string,DashboardEntityMetadata|undefined>; }
export function homeAssistantLanguage(hass:HomeAssistantLike|undefined):string{return hass?.locale?.language||hass?.language||'en';}
export function buildDashboardIntelligenceContextFromHass(document:FrakonDashboardDocument,hass:HomeAssistantLike|undefined,options:DashboardIntelligenceSignalBridgeOptions):DashboardIntelligenceContext{const states:Record<string,IntelligenceHomeAssistantState|undefined>={};for(const[entityId,source]of Object.entries(hass?.states??{})){states[entityId]={entity_id:source.entity_id,state:source.state,attributes:source.attributes,last_changed:source.last_changed};}return buildAutomaticDashboardIntelligenceContext(document,states,{device:options.device,tracker:options.tracker,now:options.now,entityMetadata:options.entityMetadata});}
export async function loadHomeAssistantEntityMetadata(hass:HomeAssistantLike|undefined):Promise<Record<string,DashboardEntityMetadata>>{if(!hass?.callWS)return{};try{const[entities,devices,areas]=await Promise.all([hass.callWS<HomeAssistantEntityRegistryEntry[]>({type:'config/entity_registry/list'}),hass.callWS<HomeAssistantDeviceRegistryEntry[]>({type:'config/device_registry/list'}),hass.callWS<HomeAssistantAreaRegistryEntry[]>({type:'config/area_registry/list'})]);const deviceById=new Map(devices.map(device=>[device.id,device])),areaById=new Map(areas.map(area=>[area.area_id,area.name])),metadata:Record<string,DashboardEntityMetadata>={};for(const entity of entities){const device=entity.device_id?deviceById.get(entity.device_id):undefined,areaId=entity.area_id??device?.area_id??undefined,areaName=areaId?areaById.get(areaId):undefined,deviceName=device?.name_by_user??device?.name??undefined;if(areaName||deviceName)metadata[entity.entity_id]={areaName,deviceName};}return metadata;}catch{return{};}}
export function referencedEntityIds(document:FrakonDashboardDocument):string[]{const ids=new Set<string>();for(const item of document.items)for(const entityId of entityIdsForItem(item))ids.add(entityId);return[...ids];}
function entityIdsForItem(item:FrakonGridItem):string[]{const card=item.card as unknown as Record<string,unknown>;const ids:string[]=[];const entity=card.entity;if(typeof entity==='string'&&entity.includes('.'))ids.push(entity);const entities=card.entities;if(Array.isArray(entities))for(const value of entities){if(typeof value==='string'&&value.includes('.'))ids.push(value);else if(value&&typeof value==='object'){const candidate=(value as Record<string,unknown>).entity;if(typeof candidate==='string'&&candidate.includes('.'))ids.push(candidate);}}return ids;}
