import { buildAutomaticDashboardIntelligenceContext, type HomeAssistantStateLike as IntelligenceHomeAssistantState } from '../dashboard/dashboard-intelligence-signals';
import type { DashboardDeviceContext, DashboardEntityMetadata, DashboardIntelligenceContext } from '../dashboard/dashboard-intelligence';
import type { DashboardInteractionTracker } from '../dashboard/dashboard-interaction-tracker';
import type { FrakonDashboardDocument, FrakonGridItem } from '../dashboard/layout-model';
export interface HomeAssistantStateLike { entity_id:string; state:string; attributes?:Record<string,unknown>; last_changed?:string }
export interface HomeAssistantLike { states:Record<string,HomeAssistantStateLike>; language?:string; locale?:{language?:string}; callWS?<T>(message:Record<string,unknown>):Promise<T>; callService?(domain:string,service:string,data?:Record<string,unknown>):Promise<unknown>|unknown }
export interface HomeAssistantEntityRegistryEntry { entity_id:string; device_id?:string|null; area_id?:string|null }
export interface HomeAssistantDeviceRegistryEntry { id:string; area_id?:string|null; name?:string|null; name_by_user?:string|null }
export interface HomeAssistantAreaRegistryEntry { area_id:string; name:string }
export interface DashboardIntelligenceSignalBridgeOptions { device:DashboardDeviceContext; tracker?:Pick<DashboardInteractionTracker,'snapshot'>; now?:number; entityMetadata?:Record<string,DashboardEntityMetadata|undefined> }
export function homeAssistantLanguage(hass:HomeAssistantLike|undefined):string{return hass?.locale?.language||hass?.language||'en'}
export function buildDashboardIntelligenceContextFromHass(document:FrakonDashboardDocument,hass:HomeAssistantLike|undefined,options:DashboardIntelligenceSignalBridgeOptions):DashboardIntelligenceContext { const states:Record<string,IntelligenceHomeAssistantState|undefined>={}; for(const[entityId,source]of Object.entries(hass?.states??{})) states[entityId]={entity_id:source.entity_id||entityId,state:source.state,attributes:source.attributes??{},last_changed:source.last_changed}; return buildAutomaticDashboardIntelligenceContext(document,{device:options.device,now:options.now,interactions:options.tracker?.snapshot(options.now),states,entityMetadata:options.entityMetadata}); }
export async function loadHomeAssistantEntityMetadata(hass:HomeAssistantLike|undefined):Promise<Record<string,DashboardEntityMetadata>> { if(!hass?.callWS)return{}; try { const[entities,devices,areas]=await Promise.all([hass.callWS<HomeAssistantEntityRegistryEntry[]>({type:'config/entity_registry/list'}),hass.callWS<HomeAssistantDeviceRegistryEntry[]>({type:'config/device_registry/list'}),hass.callWS<HomeAssistantAreaRegistryEntry[]>({type:'config/area_registry/list'})]); return resolveHomeAssistantEntityMetadata(entities,devices,areas); } catch { return{}; } }
export function resolveHomeAssistantEntityMetadata(entities:HomeAssistantEntityRegistryEntry[],devices:HomeAssistantDeviceRegistryEntry[],areas:HomeAssistantAreaRegistryEntry[]):Record<string,DashboardEntityMetadata> { const devicesById=new Map(devices.map(d=>[d.id,d])),areasById=new Map(areas.map(a=>[a.area_id,a])),result:Record<string,DashboardEntityMetadata>={}; for(const entity of entities){if(!entity.entity_id)continue;const device=entity.device_id?devicesById.get(entity.device_id):undefined,areaId=entity.area_id||device?.area_id||undefined,areaName=areaId?areasById.get(areaId)?.name:undefined,deviceName=cleanName(device?.name_by_user)||cleanName(device?.name)||undefined;if(areaName||deviceName)result[entity.entity_id]={...(areaName?{areaName}:{}),...(deviceName?{deviceName}:{})};} return result; }
export function extractDashboardItemEntityIds(item:FrakonGridItem):string[] { const ids=new Set<string>(); collectEntityIds(item.card,ids,new Set<object>()); return[...ids].sort(); }
function cleanName(value:string|null|undefined):string|undefined{return typeof value==='string'&&value.trim()?value.trim():undefined}
function collectEntityIds(value:unknown,ids:Set<string>,visited:Set<object>):void { if(typeof value==='string'){if(/^[a-z0-9_]+\.[a-z0-9_]+$/i.test(value))ids.add(value);return;} if(!value||typeof value!=='object'||visited.has(value))return; visited.add(value); if(Array.isArray(value)){for(const entry of value)collectEntityIds(entry,ids,visited);return;} for(const entry of Object.values(value))collectEntityIds(entry,ids,visited); }
