import { LitElement, css, html, nothing } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { createDashboardEmergencyFocusState,dashboardEmergencyFocusIndex,dashboardEmergencyFocusSignature,nextDashboardEmergencyFocusTarget,type DashboardEmergencyFocusState } from '../../../src/dashboard/dashboard-emergency-focus';
import { acknowledgeDashboardEmergencyHistory,dashboardEmergencyDuration,updateDashboardEmergencyHistory,type DashboardEmergencyHistoryState } from '../../../src/dashboard/dashboard-emergency-history';
import { clearDashboardEmergencyHistory,loadDashboardEmergencyHistory,saveDashboardEmergencyHistory } from '../../../src/dashboard/dashboard-emergency-history-storage';
import { resolveDashboardEmergencyAction,type DashboardEmergencyActionResolution } from '../../../src/dashboard/dashboard-emergency-action-resolver';
import { dashboardEmergencyUiStrings } from '../../../src/dashboard/dashboard-emergency-ui-i18n';
import type { DashboardDeviceContext,DashboardEntityMetadata,DashboardIntelligenceContext } from '../../../src/dashboard/dashboard-intelligence';
import type { DashboardIntelligenceUrgencyDiagnostic } from '../../../src/dashboard/dashboard-intelligence-stabilizer';
import type { DashboardInteractionTracker } from '../../../src/dashboard/dashboard-interaction-tracker';
import type { FrakonDashboardDocument } from '../../../src/dashboard/layout-model';
import { homeAssistantLanguage,loadHomeAssistantEntityMetadata,type HomeAssistantLike } from '../../../src/home-assistant/dashboard-intelligence-signal-bridge';
import type { FrakonDashboardEmergencyCardActionDetail,FrakonDashboardEmergencyEntityActionDetail,FrakonDashboardEmergencyHistoryImportDetail,FrakonDashboardEmergencyRecommendedActionDetail } from './dashboard-emergency-audit-panel';
import type { FrakonDashboardIntelligenceContextChangedDetail,FrakonDashboardIntelligenceStabilizationStatusDetail } from './dashboard-intelligence-signal-bridge';
import './dashboard-card-locator';import './dashboard-emergency-audit-panel';import './dashboard-emergency-focus-bridge';import './dashboard-intelligence-safe-panel';import './dashboard-intelligence-signal-bridge';
@customElement('frakon-dashboard-intelligence-live-panel') export class FrakonDashboardIntelligenceLivePanel extends LitElement{
 @property({attribute:false}) document?:FrakonDashboardDocument;@property({attribute:false}) hass?:HomeAssistantLike;@property({attribute:false}) tracker?:Pick<DashboardInteractionTracker,'snapshot'>;@property() device:DashboardDeviceContext='desktop';@property({type:Number}) urgencyConfirmMs=5_000;@property({type:Number}) urgencyReleaseMs=15_000;@property({type:Number}) minimumEmissionIntervalMs=2_000;@property({type:Boolean}) emergencyAutoFocus=true;@property({type:Number}) emergencyHistoryLimit=100;
 @state() private automaticContext?:DashboardIntelligenceContext;@state() private diagnostics:DashboardIntelligenceUrgencyDiagnostic[]=[];@state() private nextEvaluationAt?:number;@state() private emergencyActiveItemId='';@state() private emergencyFocusToken=0;@state() private emergencyRestoreToken=0;@state() private locatorItemId='';@state() private locatorToken=0;@state() private acknowledgedSignatures:string[]=[];@state() private emergencyHistory:DashboardEmergencyHistoryState={active:[],recent:[]};@state() private entityMetadata:Record<string,DashboardEntityMetadata>={};@state() private actionResolution?:DashboardEmergencyActionResolution;
 static styles=css`:host{display:block}.status{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:10px;padding:9px 11px;border:1px solid rgb(105 167 255 / 18%);border-radius:10px;background:rgb(105 167 255 / 6%);font:600 11px/1.4 Inter,system-ui,sans-serif}.pill{padding:4px 7px;border-radius:999px;background:rgb(255 255 255 / 7%)}.confirming{color:#9ec8ff}.cooldown{color:#ffc27a}.stable{color:#8be1b4}.critical{color:#ff8f8f;background:rgb(255 91 91 / 12%)}.next{margin-left:auto;opacity:.65}.emergency-controls{display:flex;gap:7px;flex-wrap:wrap;margin:0 0 10px}.history{margin-bottom:10px}.history-entry{padding:6px}.history-empty{opacity:.55}`;
 connectedCallback(){super.connectedCallback();this.emergencyHistory=loadDashboardEmergencyHistory(this.browserStorage(),{recentLimit:this.emergencyHistoryLimit});this.acknowledgedSignatures=this.emergencyHistory.active.filter(e=>e.acknowledgedAt!==undefined).map(e=>e.signature);void this.refreshMetadata();}
 protected updated(changed:Map<PropertyKey,unknown>){if(changed.has('hass'))void this.refreshMetadata();}
 private async refreshMetadata(){this.entityMetadata=await loadHomeAssistantEntityMetadata(this.hass);}
 private onContextChanged(event:CustomEvent<FrakonDashboardIntelligenceContextChangedDetail>){this.automaticContext=event.detail.context;const focus=this.emergencyFocus(event.detail.context),active=new Set(focus.targets.map(dashboardEmergencyFocusSignature));this.acknowledgedSignatures=this.acknowledgedSignatures.filter(s=>active.has(s));this.setEmergencyHistory(updateDashboardEmergencyHistory(this.emergencyHistory,focus,Date.now(),this.acknowledgedSignatures,this.emergencyHistoryLimit));if(!focus.active){this.emergencyActiveItemId='';return}if(!focus.targets.some(t=>t.itemId===this.emergencyActiveItemId))this.emergencyActiveItemId=focus.primary?.itemId??'';}
 private onStabilizationStatus(event:CustomEvent<FrakonDashboardIntelligenceStabilizationStatusDetail>){this.diagnostics=event.detail.diagnostics;this.nextEvaluationAt=event.detail.nextEvaluationAt;}
 private emergencyFocus(context=this.automaticContext):DashboardEmergencyFocusState{return this.document?createDashboardEmergencyFocusState(this.document,context):{active:false,targets:[]}} private currentEmergencyItemId(f:DashboardEmergencyFocusState){return this.emergencyActiveItemId&&f.targets.some(t=>t.itemId===this.emergencyActiveItemId)?this.emergencyActiveItemId:f.primary?.itemId??''} private currentEmergencyTarget(f:DashboardEmergencyFocusState){return f.targets.find(t=>t.itemId===this.currentEmergencyItemId(f))??f.primary} private moveEmergencyFocus(d:1|-1){const f=this.emergencyFocus(),t=nextDashboardEmergencyFocusTarget(f,this.currentEmergencyItemId(f),d);if(t){this.emergencyActiveItemId=t.itemId;this.emergencyFocusToken++}} private restoreEmergencyView(){this.emergencyRestoreToken++} private refocusEmergencyView(){this.emergencyFocusToken++}
 private acknowledgeEmergency(f:DashboardEmergencyFocusState){const t=this.currentEmergencyTarget(f);if(!t)return;const s=dashboardEmergencyFocusSignature(t);if(!this.acknowledgedSignatures.includes(s))this.acknowledgedSignatures=[...this.acknowledgedSignatures,s];this.setEmergencyHistory(acknowledgeDashboardEmergencyHistory(this.emergencyHistory,s,Date.now()));}
 private setEmergencyHistory(h:DashboardEmergencyHistoryState){this.emergencyHistory=saveDashboardEmergencyHistory(this.browserStorage(),h,{recentLimit:this.emergencyHistoryLimit})} private importEmergencyHistory(e:CustomEvent<FrakonDashboardEmergencyHistoryImportDetail>){this.setEmergencyHistory(e.detail.history)} private clearEmergencyHistory(){clearDashboardEmergencyHistory(this.browserStorage());this.emergencyHistory={active:[],recent:[]};this.acknowledgedSignatures=[]}
 private onAuditCardAction(e:CustomEvent<FrakonDashboardEmergencyCardActionDetail>){const{action,itemId,active}=e.detail;if(!this.document?.items.some(i=>i.id===itemId))return;if(action==='focus'&&active){const f=this.emergencyFocus();if(f.targets.some(t=>t.itemId===itemId)){this.emergencyActiveItemId=itemId;this.emergencyFocusToken++;return}}this.locatorItemId=itemId;this.locatorToken++;}
 private onAuditEntityAction(e:CustomEvent<FrakonDashboardEmergencyEntityActionDetail>){const entityId=e.detail.entityId.trim();if(entityId.includes('.'))this.dispatchEvent(new CustomEvent('hass-more-info',{detail:{entityId},bubbles:true,composed:true}))}
 private onRecommendedAction(e:CustomEvent<FrakonDashboardEmergencyRecommendedActionDetail>){this.actionResolution=resolveDashboardEmergencyAction(e.detail.recommendation,e.detail.entry,this.hass?.states??{},this.entityMetadata);}
 private browserStorage():Storage|undefined{try{return typeof window!=='undefined'?window.localStorage:undefined}catch{return undefined}}
 private renderStatus(){const s=dashboardEmergencyUiStrings(homeAssistantLanguage(this.hass)),c=this.diagnostics.filter(d=>d.phase==='confirming').length,cd=this.diagnostics.filter(d=>d.phase==='cooldown').length,u=this.diagnostics.filter(d=>d.phase==='stable'&&d.stableUrgent).length,cr=this.diagnostics.filter(d=>d.stableUrgent&&d.severity==='critical').length;if(!c&&!cd&&!u)return nothing;return html`<div class="status">${cr?html`<span class="pill critical">${cr} ${s.critical}</span>`:nothing}${u?html`<span class="pill stable">${u} ${s.urgent}</span>`:nothing}${c?html`<span class="pill confirming">${c} ${s.confirming}</span>`:nothing}${cd?html`<span class="pill cooldown">${cd} ${s.coolingDown}</span>`:nothing}</div>`}
 private renderEmergencyControls(f:DashboardEmergencyFocusState){if(!f.active)return nothing;const s=dashboardEmergencyUiStrings(homeAssistantLanguage(this.hass)),id=this.currentEmergencyItemId(f),i=dashboardEmergencyFocusIndex(f,id),t=this.currentEmergencyTarget(f),ack=t?this.acknowledgedSignatures.includes(dashboardEmergencyFocusSignature(t)):false;return html`<div class="emergency-controls"><strong>${s.criticalPosition(Math.max(0,i)+1,f.targets.length,id)}</strong><button @click=${()=>this.moveEmergencyFocus(-1)}>${s.previous}</button><button @click=${()=>this.moveEmergencyFocus(1)}>${s.next}</button><button @click=${this.restoreEmergencyView}>${s.returnToPreviousView}</button><button @click=${this.refocusEmergencyView}>${s.focusAgain}</button><button ?disabled=${ack} @click=${()=>this.acknowledgeEmergency(f)}>${ack?s.acknowledged:s.acknowledge}</button></div>`}
 private renderEmergencyHistory(){const s=dashboardEmergencyUiStrings(homeAssistantLanguage(this.hass));if(!this.emergencyHistory.active.length&&!this.emergencyHistory.recent.length)return nothing;return html`<section class="history"><strong>${s.history}</strong>${this.emergencyHistory.active.map(e=>html`<div class="history-entry">${e.itemId} · ${Math.round(dashboardEmergencyDuration(e)/1000)}s</div>`)}</section>`}
 render(){const f=this.emergencyFocus(),id=this.currentEmergencyItemId(f),locale=homeAssistantLanguage(this.hass);return html`<frakon-dashboard-intelligence-signal-bridge .hass=${this.hass} .document=${this.document} .tracker=${this.tracker} .device=${this.device} .urgencyConfirmMs=${this.urgencyConfirmMs} .urgencyReleaseMs=${this.urgencyReleaseMs} .minimumEmissionIntervalMs=${this.minimumEmissionIntervalMs} @frakon-dashboard-intelligence-context-changed=${this.onContextChanged} @frakon-dashboard-intelligence-stabilization-status=${this.onStabilizationStatus}></frakon-dashboard-intelligence-signal-bridge><frakon-dashboard-emergency-focus-bridge .focusState=${f} .document=${this.document} .autoFocus=${this.emergencyAutoFocus} .activeItemId=${id} .locale=${locale} .acknowledgedSignatures=${this.acknowledgedSignatures} .focusToken=${this.emergencyFocusToken} .restoreToken=${this.emergencyRestoreToken}></frakon-dashboard-emergency-focus-bridge><frakon-dashboard-card-locator .document=${this.document} .itemId=${this.locatorItemId} .locateToken=${this.locatorToken}></frakon-dashboard-card-locator>${this.renderStatus()}${this.renderEmergencyControls(f)}${this.renderEmergencyHistory()}<frakon-dashboard-emergency-audit-panel .history=${this.emergencyHistory} .locale=${locale} .recentLimit=${this.emergencyHistoryLimit} .actionResolution=${this.actionResolution} @frakon-dashboard-emergency-history-import=${this.importEmergencyHistory} @frakon-dashboard-emergency-history-clear=${this.clearEmergencyHistory} @frakon-dashboard-emergency-card-action=${this.onAuditCardAction} @frakon-dashboard-emergency-entity-action=${this.onAuditEntityAction} @frakon-dashboard-emergency-recommended-action=${this.onRecommendedAction}></frakon-dashboard-emergency-audit-panel><frakon-dashboard-intelligence-safe-panel .document=${this.document} .automaticContext=${this.automaticContext}></frakon-dashboard-intelligence-safe-panel>`}}
declare global{interface HTMLElementTagNameMap{'frakon-dashboard-intelligence-live-panel':FrakonDashboardIntelligenceLivePanel}}
